---
- name: install vscode
  hosts: localhost

  tasks:
  - name: apt add key
    ansible.builtin.apt_key:
      id: EB3E94ADBE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: add code ppa
    become: yes
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] http://packages.microsoft.com/repos/code stable main
      state: present
  
  - name: download ms teams
    become: yes
    ansible.builtin.apt:
      pkg: code
      update_cache: yes
